export default [
  {
    key: 'asimAdvancedJS',
    linkText: 'Advanced Javascript',
    linkUrl: 'https://www.udemy.com/javascript-advanced/',
    secondaryInfo: 'Asim Hussain',
    auxInfo:
      'Asim explains advanced JavaScript language features in an enjoyable and understandable way.',
  },
  {
    key: 'schogerRefactoringUI',
    linkText: 'Refactoring UI',
    linkUrl: 'https://refactoringui.com/book/',
    secondaryInfo: 'Adam Wathan & Steve Schoger',
    auxInfo: 'An excellent resource to be a better designer as a developer.',
  },
  {
    key: 'wesAdvancedReact',
    linkText: 'Advanced React and GraphQL',
    linkUrl: 'https://advancedreact.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes uses a very interesting GraphQL stack to build an online store app.',
  },
  {
    key: 'codingPracticeReact',
    linkText: 'The React practice course',
    linkUrl: 'https://www.udemy.com/the-react-practice-course-learn-by-building-projects/',
    secondaryInfo: 'Coding Revolution',
    auxInfo: 'The author builds three projects, of increasing complexity, using React.',
  },
  {
    key: 'scottProGtasby',
    linkText: 'Pro Gatsby',
    linkUrl: 'https://www.leveluptutorials.com/tutorials/pro-gatsby',
    secondaryInfo: 'Scott Tolinski',
    auxInfo: 'Scott takes the awesome static site generator Gatsby for a spin to build a blog.',
  },
  {
    key: 'aliceaUnderstandJavascript',
    linkText: 'JavaScript - Understanding the Weird Parts',
    linkUrl: 'https://www.udemy.com/understand-javascript/',
    secondaryInfo: 'Anthony Alicea',
    auxInfo:
      'Anthony Alicea explains the fundamental concepts of the JavaScript language in great detail.',
  },
  {
    key: 'griderReactRedux',
    linkText: 'Modern React with Redux',
    linkUrl: 'https://www.udemy.com/react-redux/',
    secondaryInfo: 'Stephen Grider',
    auxInfo:
      'Stephen Grider explains React and Redux with his very personal and engaging teaching style.',
  },
  {
    key: 'griderWebpack2',
    linkText: "Webpack 2: The Complete Developer's Guide",
    linkUrl: 'https://www.udemy.com/webpack-2-the-complete-developers-guide/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider manages to explain the sometimes hard to grasp Webpack.',
  },
  {
    key: 'griderReactNative',
    linkText: 'The Complete React Native and Redux Course',
    linkUrl: 'https://www.udemy.com/the-complete-react-native-and-redux-course/',
    secondaryInfo: 'Stephen Grider',
    auxInfo:
      'Stephen Grider teaches React Native in his with his very personal and engaging teaching style.',
  },
  {
    key: 'griderReactNativeAdvanced',
    linkText: 'React Native: Advanced Concepts',
    linkUrl: 'https://www.udemy.com/react-native-advanced/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider teaches some React Native advanced concepts.',
  },
  {
    key: 'griderNode',
    linkText: 'Node with React: Fullstack Web Development',
    linkUrl: 'https://www.udemy.com/node-with-react-fullstack-web-development/',
    secondaryInfo: 'Stephen Grider',
    auxInfo:
      'Stephen Grider covers the popular fullstack tech stack: React, Redux, Express, and Mongo.',
  },
  {
    key: 'griderReactAdvanced',
    linkText: 'Advanced React and Redux',
    linkUrl: 'https://www.udemy.com/react-redux-tutorial/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider gives a detailed walkthrough on advanced React and Redux concepts.',
  },
  {
    key: 'millerTestingCookbook',
    linkText: 'React Testing Cookbook',
    linkUrl: 'https://egghead.io/courses/react-testing-cookbook',
    secondaryInfo: 'Trevor Miller',
    auxInfo: 'Trevor Miller takes a look into testing React applications.',
  },
  {
    key: 'mykolaArrayReduce',
    linkText: 'Reduce Data with Javascript Array#reduce',
    linkUrl: 'https://egghead.io/courses/reduce-data-with-javascript-array-reduce',
    secondaryInfo: 'Mykola Bilokonsky',
    auxInfo: 'Mykola Bilokonsky digs deep into the Array#reduce method in JavaScript.',
  },
  {
    key: 'madalloneReactRouterV4',
    linkText: 'Add routing to React apps using React Router v4',
    linkUrl: 'https://egghead.io/courses/add-routing-to-react-apps-using-react-router-v4',
    secondaryInfo: 'Joe Maddalone',
    auxInfo: 'Joe Maddalone teaches the basics of React Router v4.',
  },
  {
    key: 'abramovRedux',
    linkText: 'Getting Started with Redux',
    linkUrl: 'https://egghead.io/courses/getting-started-with-redux',
    secondaryInfo: 'Dan Abramov',
    auxInfo: 'Dan Abramov shows you the fundamentals of Redux.',
  },
  {
    key: 'abramovIdiomaticRedux',
    linkText: 'Building React Applications with Idiomatic Redux',
    linkUrl: 'https://egghead.io/courses/building-react-applications-with-idiomatic-redux',
    secondaryInfo: 'Dan Abramov',
    auxInfo: "This course shows better practices straight from the library's creator Dan Abramov.",
  },
  {
    key: 'wesCSSGrid',
    linkText: 'CSS Grid',
    linkUrl: 'https://cssgrid.io/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes teaches everything there is to learn about CSS Grid.',
  },
  {
    key: 'wesLearnNode',
    linkText: 'Learn Node',
    linkUrl: 'https://learnnode.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes teaches how to build apps with Node.js, Express, MongoDB, and friends.',
  },
  {
    key: 'wesES6',
    linkText: 'ES6 for everyone',
    linkUrl: 'https://es6.io/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes gives a fun and approachable look at all ES6 has to offer.',
  },
  {
    key: 'wesReact',
    linkText: 'React for beginners',
    linkUrl: 'https://reactforbeginners.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo:
      'Wes gives step-by-step guide to build real world React.js + Firebase apps and website components.',
  },
  {
    key: 'wesRedux',
    linkText: 'Learn Redux',
    linkUrl: 'https://learnredux.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes explains the core ideas behind Redux, React Router and React.js.',
  },
  {
    key: 'wesJS30',
    linkText: 'Javascript 30',
    linkUrl: 'https://javascript30.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'The popular Wes 30-day vanilla JS coding challenge.',
  },
  {
    key: 'coryReactRedux',
    linkText: 'Building Applications with React and Redux in ES6',
    linkUrl: 'https://www.pluralsight.com/courses/react-redux-react-router-es6',
    secondaryInfo: 'Cory House',
    auxInfo:
      'Cory teaches how to use Redux, React Router, and ES6 to build a real world app with React.',
  },
];
