import { v4 as uuidv4 } from 'uuid';

const courses = [
  {
    key: uuidv4(),
    linkText: 'Just Javascript',
    linkUrl: 'https://justjavascript.com/',
    secondaryInfo: 'Dan Abramov and Maggie Appleton',
    auxInfo: 'Dan and Maggie offer us a fresh way to visualise and develop bullet proof mental models about JavaScript.',
  },
  {
    key: uuidv4(),
    linkText: 'Create a Database Schema using the Amplify Admin UI',
    linkUrl: 'https://egghead.io/lessons/aws-create-a-database-schema-using-the-amplify-admin-ui',
    secondaryInfo: 'Ali Spittel',
    auxInfo: 'An excellent and concise course about AWS Amplify Admin UI.',
  },
  {
    key: uuidv4(),
    linkText: 'Learn CSS',
    linkUrl: 'https://web.dev/learn/css/',
    secondaryInfo: 'web.dev',
    auxInfo: 'An evergreen CSS course and reference to level up your web styling expertise.',
  },
  {
    key: uuidv4(),
    linkText: 'SQL and PostgreSQL: The Complete Developer\'s Guide',
    linkUrl: 'https://www.udemy.com/course/sql-and-postgresql/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'A comprehensive course about SQL and PostgreSQL by Stephen Grider.',
  },
  {
    key: uuidv4(),
    linkText: 'End-to-End Security with Auth0',
    linkUrl: 'https://courses.reactsecurity.io/courses/end-to-end-security-with-auth0',
    secondaryInfo: 'Ryan Chenkie',
    auxInfo: 'Ryan Chenkie guides us through the process of adding Auth0 for authentication and authorization.',
  },
  {
    key: uuidv4(),
    linkText: 'Learn and Understand NodeJS',
    linkUrl: 'https://www.udemy.com/course/understand-nodejs/',
    secondaryInfo: 'Anthony Alicea',
    auxInfo: 'I must confess, I\'m a big fan of Anthony\'s teaching style. This course is another mandatory one to watch.',
  },
  {
    key: uuidv4(),
    linkText: 'The Complete React Native + Hooks',
    linkUrl: 'https://www.udemy.com/course/the-complete-react-native-and-redux-course/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider guides us into a great journey through react-native, using the latest React features.',
  },
  {
    key: uuidv4(),
    linkText: 'Construct Sturdy UIs with XState',
    linkUrl: 'https://egghead.io/courses/construct-sturdy-uis-with-xstate',
    secondaryInfo: 'Isaac Mann',
    auxInfo: 'Concise and valuable course about Xstate and state machines. The author explains the main features of the library by using great example apps, as usual with a great pace.',
  },
  {
    key: uuidv4(),
    linkText: 'Introduction to State Machines Using XState',
    linkUrl: 'https://egghead.io/courses/introduction-to-state-machines-using-xstate',
    secondaryInfo: 'Kyle Shevlin',
    auxInfo: 'Another excellent course from Kyle Shevlin, this time around about state machines and Xstate.',
  },
  {
    key: uuidv4(),
    linkText: 'NestJS Zero to Hero',
    linkUrl: 'https://www.udemy.com/course/nestjs-zero-to-hero/',
    secondaryInfo: 'Ariel Weinberger',
    auxInfo: 'NestJS is definitely a solid node framework. Ariel gives a great introduction to Nest in this course. The course is easy to digest with a great pace.',
  },
  {
    key: uuidv4(),
    linkText: 'Testing JavaScript',
    linkUrl: 'https://testingjavascript.com/',
    secondaryInfo: 'Kent C. Dodds',
    auxInfo: 'Probably, the best course about JavaScript testing. Among all the great things this course was to offer, I found the pace to be incredible - so much high quality knowledge in such a short amount of time.',
  },
  {
    key: uuidv4(),
    linkText: 'Typescript: The Complete Developer\'s Guide',
    linkUrl: 'https://www.udemy.com/course/typescript-the-complete-developers-guide/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'One more extremely high quality course from Stephen about Typescript, an invaluable tool to write good quality code.',
  },
  {
    key: uuidv4(),
    linkText: 'Async React with Redux Saga',
    linkUrl: 'https://egghead.io/courses/async-react-with-redux-saga',
    secondaryInfo: 'Tyler Clark',
    auxInfo: 'A great course about the super powers of redux-saga.',
  },
  {
    key: uuidv4(),
    linkText: 'How to Write an Open Source JavaScript Library',
    linkUrl: 'https://egghead.io/courses/how-to-write-an-open-source-javascript-library',
    secondaryInfo: 'Kent C. Dodds',
    auxInfo: 'Excellent course by the one and only Kent C. Dodds, where he explains how to publish an npm package.',
  },
  {
    key: uuidv4(),
    linkText: 'Modern JavaScript Tooling with React',
    linkUrl: 'https://egghead.io/courses/modern-javascript-tooling-with-react',
    secondaryInfo: 'Andy Van Slaars',
    auxInfo: 'In this course, starting from an empty directory, Andy builds a powerful boilerplate project.',
  },
  {
    key: uuidv4(),
    linkText: 'JavaScript ES2019 in Practice',
    linkUrl: 'https://egghead.io/courses/javascript-es2019-in-practice',
    secondaryInfo: 'Mike Sherov',
    auxInfo: 'A course about all latest JavaScript features published with ES2019.',
  },
  {
    key: uuidv4(),
    linkText: 'Productive Git for Developers',
    linkUrl: 'https://egghead.io/courses/productive-git-for-developers',
    secondaryInfo: 'Juri Strumpflohner',
    auxInfo: 'A concise and helpful course about Git with a lot of great tips and Git workflows.',
  },
  {
    key: uuidv4(),
    linkText: 'React Testing with Jest and Enzyme',
    linkUrl: 'https://www.udemy.com/react-testing-with-jest-and-enzyme/',
    secondaryInfo: 'Bonnie Schulkin',
    auxInfo: 'An excellent course about testing React apps with Jest and Enzyme using the TDD strategy.',
  },
  {
    key: uuidv4(),
    linkText: 'Node.js: The Complete Guide to Build RESTful APIs',
    linkUrl: 'https://www.udemy.com/nodejs-master-class',
    secondaryInfo: 'Mosh Hamedani',
    auxInfo: 'A great course to learn the fundamentals of building RESTful APIs in Node, Express and MongoDB.',
  },
  {
    key: uuidv4(),
    linkText: 'Universal React with Next.js - The Ultimate Guide',
    linkUrl: 'https://www.udemy.com/universal-react-with-nextjs-the-ultimate-guide',
    secondaryInfo: 'Reed Barger',
    auxInfo: 'A course on Next.js from Reed Barger. Almost 10h of content and a total of 6 projects makes this a comprehensive course.',
  },
  {
    key: uuidv4(),
    linkText: 'Advanced Javascript',
    linkUrl: 'https://www.udemy.com/javascript-advanced/',
    secondaryInfo: 'Asim Hussain',
    auxInfo: 'Asim explains advanced JavaScript language features in an enjoyable and understandable way.',
  },
  {
    key: uuidv4(),
    linkText: 'Refactoring UI',
    linkUrl: 'https://refactoringui.com/book/',
    secondaryInfo: 'Adam Wathan & Steve Schoger',
    auxInfo: 'An excellent resource to be a better designer as a developer.',
  },
  {
    key: uuidv4(),
    linkText: 'Advanced React and GraphQL',
    linkUrl: 'https://advancedreact.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes uses a very interesting GraphQL stack to build an online store app.',
  },
  {
    key: uuidv4(),
    linkText: 'The React practice course',
    linkUrl: 'https://www.udemy.com/the-react-practice-course-learn-by-building-projects/',
    secondaryInfo: 'Coding Revolution',
    auxInfo: 'The author builds three projects, of increasing complexity, using React.',
  },
  {
    key: uuidv4(),
    linkText: 'Pro Gatsby',
    linkUrl: 'https://www.leveluptutorials.com/tutorials/pro-gatsby',
    secondaryInfo: 'Scott Tolinski',
    auxInfo: 'Scott takes the awesome static site generator Gatsby for a spin to build a blog.',
  },
  {
    key: uuidv4(),
    linkText: 'JavaScript - Understanding the Weird Parts',
    linkUrl: 'https://www.udemy.com/understand-javascript/',
    secondaryInfo: 'Anthony Alicea',
    auxInfo: 'Anthony Alicea explains the fundamental concepts of the JavaScript language in great detail.',
  },
  {
    key: uuidv4(),
    linkText: 'Modern React with Redux',
    linkUrl: 'https://www.udemy.com/react-redux/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider explains React and Redux with his very personal and engaging teaching style.',
  },
  {
    key: uuidv4(),
    linkText: "Webpack 2: The Complete Developer's Guide",
    linkUrl: 'https://www.udemy.com/webpack-2-the-complete-developers-guide/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider manages to explain the sometimes hard to grasp Webpack.',
  },
  {
    key: uuidv4(),
    linkText: 'The Complete React Native and Redux Course',
    linkUrl: 'https://www.udemy.com/the-complete-react-native-and-redux-course/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider teaches React Native in his with his very personal and engaging teaching style.',
  },
  {
    key: uuidv4(),
    linkText: 'React Native: Advanced Concepts',
    linkUrl: 'https://www.udemy.com/react-native-advanced/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider teaches some React Native advanced concepts.',
  },
  {
    key: uuidv4(),
    linkText: 'Node with React: Fullstack Web Development',
    linkUrl: 'https://www.udemy.com/node-with-react-fullstack-web-development/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider covers the popular fullstack tech stack: React, Redux, Express, and Mongo.',
  },
  {
    key: uuidv4(),
    linkText: 'Advanced React and Redux',
    linkUrl: 'https://www.udemy.com/react-redux-tutorial/',
    secondaryInfo: 'Stephen Grider',
    auxInfo: 'Stephen Grider gives a detailed walkthrough on advanced React and Redux concepts.',
  },
  {
    key: uuidv4(),
    linkText: 'React Testing Cookbook',
    linkUrl: 'https://egghead.io/courses/react-testing-cookbook',
    secondaryInfo: 'Trevor Miller',
    auxInfo: 'Trevor Miller takes a look into testing React applications.',
  },
  {
    key: uuidv4(),
    linkText: 'Reduce Data with Javascript Array#reduce',
    linkUrl: 'https://egghead.io/courses/reduce-data-with-javascript-array-reduce',
    secondaryInfo: 'Mykola Bilokonsky',
    auxInfo: 'Mykola Bilokonsky digs deep into the Array#reduce method in JavaScript.',
  },
  {
    key: uuidv4(),
    linkText: 'Add routing to React apps using React Router v4',
    linkUrl: 'https://egghead.io/courses/add-routing-to-react-apps-using-react-router-v4',
    secondaryInfo: 'Joe Maddalone',
    auxInfo: 'Joe Maddalone teaches the basics of React Router v4.',
  },
  {
    key: uuidv4(),
    linkText: 'Getting Started with Redux',
    linkUrl: 'https://egghead.io/courses/getting-started-with-redux',
    secondaryInfo: 'Dan Abramov',
    auxInfo: 'Dan Abramov shows you the fundamentals of Redux.',
  },
  {
    key: uuidv4(),
    linkText: 'Building React Applications with Idiomatic Redux',
    linkUrl: 'https://egghead.io/courses/building-react-applications-with-idiomatic-redux',
    secondaryInfo: 'Dan Abramov',
    auxInfo: "This course shows better practices straight from the library's creator Dan Abramov.",
  },
  {
    key: uuidv4(),
    linkText: 'CSS Grid',
    linkUrl: 'https://cssgrid.io/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes teaches everything there is to learn about CSS Grid.',
  },
  {
    key: uuidv4(),
    linkText: 'Learn Node',
    linkUrl: 'https://learnnode.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes teaches how to build apps with Node.js, Express, MongoDB, and friends.',
  },
  {
    key: uuidv4(),
    linkText: 'ES6 for everyone',
    linkUrl: 'https://es6.io/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes gives a fun and approachable look at all ES6 has to offer.',
  },
  {
    key: uuidv4(),
    linkText: 'React for beginners',
    linkUrl: 'https://reactforbeginners.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes gives step-by-step guide to build real world React.js + Firebase apps and website components.',
  },
  {
    key: uuidv4(),
    linkText: 'Learn Redux',
    linkUrl: 'https://learnredux.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'Wes explains the core ideas behind Redux, React Router and React.js.',
  },
  {
    key: uuidv4(),
    linkText: 'Javascript 30',
    linkUrl: 'https://javascript30.com/',
    secondaryInfo: 'Wes Bos',
    auxInfo: 'The popular Wes 30-day vanilla JS coding challenge.',
  },
  {
    key: uuidv4(),
    linkText: 'Building Applications with React and Redux in ES6',
    linkUrl: 'https://www.pluralsight.com/courses/react-redux-react-router-es6',
    secondaryInfo: 'Cory House',
    auxInfo: 'Cory teaches how to use Redux, React Router, and ES6 to build a real world app with React.',
  },
];

export default courses;
